Update patch set 1
Patch Set 1:

With the changes from the 'fix-compiling' topic, the plugin can be
compiled again (on 2015-06-06). Installing it will still fail with
[1], as gitblit and gerrit seem to use incompatible jgit versions. I
guess we'll have to wait for gitblit to update their jgit.


[1]

  com.google.gerrit.server.plugins.PluginInstallException: org.eclipse.jgit.treewalk.TreeWalk.release()V
        at com.google.gerrit.server.plugins.PluginLoader.runPlugin(PluginLoader.java:495)
        at com.google.gerrit.server.plugins.PluginLoader.installPluginFromStream(PluginLoader.java:189)
        at com.google.gerrit.sshd.commands.PluginInstallCommand.run(PluginInstallCommand.java:98)
        at com.google.gerrit.sshd.SshCommand$1.run(SshCommand.java:35)
        at com.google.gerrit.sshd.BaseCommand$TaskThunk.run(BaseCommand.java:444)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:377)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
  Caused by: java.lang.NoSuchMethodError: org.eclipse.jgit.treewalk.TreeWalk.release()V
        at com.gitblit.utils.JGitUtils.getByteContent(JGitUtils.java:777)
        at com.gitblit.utils.JGitUtils.getSparkleshareId(JGitUtils.java:2239)
        at com.gitblit.manager.RepositoryManager.loadRepositoryModel(RepositoryManager.java:956)
        at com.gitblit.manager.RepositoryManager.getRepositoryModel(RepositoryManager.java:719)
        at com.gitblit.manager.RepositoryManager.configureCommitCache(RepositoryManager.java:1959)
        at com.gitblit.manager.RepositoryManager.start(RepositoryManager.java:169)
        at com.gitblit.manager.RepositoryManager.start(RepositoryManager.java:104)
        at com.gitblit.servlet.GitblitContext.startManager(GitblitContext.java:268)
        at com.googlesource.gerrit.plugins.gitblit.GerritGitBlitContext.init(GerritGitBlitContext.java:71)
        at com.googlesource.gerrit.plugins.gitblit.GerritWicketFilter.init(GerritWicketFilter.java:85)
        at com.google.inject.servlet.FilterDefinition.init(FilterDefinition.java:112)
        at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:99)
        at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:220)
        at com.google.gerrit.httpd.plugins.HttpPluginServlet.load(HttpPluginServlet.java:189)
        at com.google.gerrit.httpd.plugins.HttpPluginServlet.install(HttpPluginServlet.java:163)
        at com.google.gerrit.httpd.plugins.HttpPluginServlet.onStartPlugin(HttpPluginServlet.java:153)
        at com.google.gerrit.server.plugins.PluginGuiceEnvironment.onStartPlugin(PluginGuiceEnvironment.java:240)
        at com.google.gerrit.server.plugins.PluginLoader.runPlugin(PluginLoader.java:484)
        ... 12 more
  fatal: Plugin failed to install. Cause: org.eclipse.jgit.treewalk.TreeWalk.release()V

Patch-set: 1
Reviewer: Christian Aistleitner <1012155@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0