Update patch set 1
Patch Set 1: Verified-1

Fails to compile here:

 [ERROR] symbol:   class LogoServlet
 [ERROR] location: package com.gitblit
 [ERROR] /home/davido/projects/gitblit/src/main/[...]/gitblit/WrappedLogoServlet.java: [22,40]

That class semms to be missing in giblit 1.4.0-SNAPSHOT:

 javap -cp <path-to>/1.4.0-SNAPSHOT/gitblit-1.4.0-SNAPSHOT.jar com.gitblit.LogoServlet
 Error:  class not found: com.gitblit.LogoServlet

Patch-set: 1