Update patch set 2
Patch Set 2: Verified-1

Still doesn't work. It seems that JGit version is too new for GitBlit. Full stack trace is here [1].

  Caused by: java.lang.NoSuchMethodError: 
  org.eclipse.jgit.lib.Repository.getRef(Ljava/lang/String;)Lorg/eclipse/jgit/lib/Ref;
	at com.syntevo.bugtraq.BugtraqConfig.getBaseConfig(BugtraqConfig.java:193)
	at com.syntevo.bugtraq.BugtraqConfig.read(BugtraqConfig.java:77)
	at com.gitblit.utils.BugtraqProcessor.processTextRegex(BugtraqProcessor.java:151)

Patch-set: 2
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1