Update patch set 1
Patch Set 1: Code-Review-1

While the plugin compiles again using this patch, upon installing the
compiled plugin in gerrit [1] I get an exception [2]. This exception
seems to stem from gerrit's switch to JGit 3 API prior to 2.6rc0.
A fix^Wmitigation for gitblit can be found at
If653098f75f604a14e7ee642e5ee3824ff601afc


[1] I tried installing via ssh in gerrit 5984a030e796098e5abd694f514dcc617c7afdfe -- that's
the commit tagged as 'v2.6-rc0'.


[2]

  com.google.gerrit.server.plugins.PluginInstallException: org/eclipse/jgit/storage/file/FileRepository
        at com.google.gerrit.server.plugins.PluginLoader.runPlugin(PluginLoader.java:381)
        at com.google.gerrit.server.plugins.PluginLoader.installPluginFromStream(PluginLoader.java:151)
        at com.google.gerrit.sshd.commands.PluginInstallCommand.run(PluginInstallCommand.java:92)
        at com.google.gerrit.sshd.SshCommand$1.run(SshCommand.java:35)
        at com.google.gerrit.sshd.BaseCommand$TaskThunk.run(BaseCommand.java:429)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
        at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:337)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
  Caused by: java.lang.NoClassDefFoundError: org/eclipse/jgit/storage/file/FileRepository
        at com.gitblit.GitBlit.configureContext(GitBlit.java:2843)
        at com.googlesource.gerrit.plugins.gitblit.GerritWicketFilter.init(GerritWicketFilter.java:91)
        at com.google.inject.servlet.FilterDefinition.init(FilterDefinition.java:114)
        at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:98)
        at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:172)
        at com.google.gerrit.httpd.plugins.HttpPluginServlet.load(HttpPluginServlet.java:175)
        at com.google.gerrit.httpd.plugins.HttpPluginServlet.install(HttpPluginServlet.java:150)
        at com.google.gerrit.httpd.plugins.HttpPluginServlet.onStartPlugin(HttpPluginServlet.java:140)
        at com.google.gerrit.server.plugins.PluginGuiceEnvironment.onStartPlugin(PluginGuiceEnvironment.java:192)
        at com.google.gerrit.server.plugins.PluginLoader.runPlugin(PluginLoader.java:370)
        ... 13 more
  Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.storage.file.FileRepository
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        ... 23 more
  fatal: plugin failed to install

Patch-set: 1
Reviewer: Gerrit User 1012155 <1012155@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=-1