Update patch set 2
Patch Set 2:

> Patch Set 2: Verified-1
> 
> Still doesn't work. It seems that JGit version is too new for GitBlit. Full stack trace is here [1].
> 
>   Caused by: java.lang.NoSuchMethodError: 
>   org.eclipse.jgit.lib.Repository.getRef(Ljava/lang/String;)Lorg/eclipse/jgit/lib/Ref;
> 	at com.syntevo.bugtraq.BugtraqConfig.getBaseConfig(BugtraqConfig.java:193)
> 	at com.syntevo.bugtraq.BugtraqConfig.read(BugtraqConfig.java:77)
> 	at com.gitblit.utils.BugtraqProcessor.processTextRegex(BugtraqProcessor.java:151)

Root cause is:

* Gitblit JGit version:

  jgit.version   : 4.1.1.201511131810-r

* Gerrit JGit version:

  4.11.0.201803080745-r.93-gcbb2e65db

Particularly, Repository.getRef(String) was discontinued, see: [1]:

  org.eclipse.jgit.lib.Repository.getRef(String)
  Use Repository.exactRef(String) or Repository.findRef(String) instead.

To rectify, we would need to bump JGit in GitBlit and adapt the code to new JGit version to be compatible with JGit version used in Gerrit core.

* [1] http://download.eclipse.org/jgit/site/4.2.0.201601211800-r/apidocs/deprecated-list.html

Patch-set: 2
Reviewer: David Ostrovsky <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>