Fix compilation errors on Gerrit 2.13.8
Makes GitBlit plugin code-compatible with Gerrit 2.13.8.
However, it wouldn't work yet as the Lucene index libraries aren't
compatible (fails with Caused by: java.lang.NoSuchFieldError: LUCENE_46)

Change-Id: I369249cb1e0ca34699f6b520a91232d3ee6584af