Update patch set 15
Patch Set 15:

It seems that this plugin is failing with

Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: javax/mail/Message
  at com.gitblit.manager.NotificationManager.<init>(NotificationManager.java:55)
  at com.gitblit.manager.NotificationManager.class(NotificationManager.java:43)
  while locating com.gitblit.manager.NotificationManager
  while locating com.gitblit.manager.INotificationManager
    for the 5th parameter of com.gitblit.manager.GitblitManager.<init>(GitblitManager.java:151)


Because gerrit core uses 1.5.6 whereas gitblit uses 1.5.1.

We should implement it so that plugins doint have access to some of the deps because they are going to break these plugins.

Patch-set: 15
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>